class StateFlagParser {
  String stateFlagParser(String state) {
    switch (state) {
      case 'AL':
        return 'assets/images/states/alabama.png';
      case 'AK':
        return 'assets/images/states/alaska.png';
      case 'AZ':
        return 'assets/images/states/arizona.png';
      case 'AR':
        return 'assets/images/states/arkansas.png';
      case 'CA':
        return 'assets/images/states/california.png';
      case 'CO':
        return 'assets/images/states/colorado.png';
      case 'CT':
        return 'assets/images/states/connecticut.png';
      case 'DE':
        return 'assets/images/states/delaware.png';
      case 'FL':
        return 'assets/images/states/florida.png';
      case 'GA':
        return 'assets/images/states/georgia.png';
      case 'HI':
        return 'assets/images/states/hawaii.png';
      case 'ID':
        return 'assets/images/states/idaho.png';
      case 'IL':
        return 'assets/images/states/illinois.png';
      case 'IN':
        return 'assets/images/states/indiana.png';
      case 'IA':
        return 'assets/images/states/iowa.png';
      case 'KS':
        return 'assets/images/states/kansas.png';
      case 'KY':
        return 'assets/images/states/kentucky.png';
      case 'LA':
        return 'assets/images/states/louisiana.png';
      case 'ME':
        return 'assets/images/states/maine.png';
      case 'MD':
        return 'assets/images/states/maryland.png';
      case 'MA':
        return 'assets/images/states/massachusetts.png';
      case 'MI':
        return 'assets/images/states/michigan.png';
      case 'MN':
        return 'assets/images/states/minnesota.png';
      case 'MS':
        return 'assets/images/states/mississippi.png';
      case 'MO':
        return 'assets/images/states/missouri.png';
      case 'MT':
        return 'assets/images/states/montana.png';
      case 'NE':
        return 'assets/images/states/nebraska.png';
      case 'NV':
        return 'assets/images/states/nevada.png';
      case 'NH':
        return 'assets/images/states/new_hampshire.png';
      case 'NJ':
        return 'assets/images/states/new_jersey.png';
      case 'NM':
        return 'assets/images/states/new_mexico.png';
      case 'NY':
        return 'assets/images/states/new_york.png';
      case 'NC':
        return 'assets/images/states/north_carolina.png';
      case 'ND':
        return 'assets/images/states/north_dakota.png';
      case 'OH':
        return 'assets/images/states/ohio.png';
      case 'OK':
        return 'assets/images/states/oklahoma.png';
      case 'OR':
        return 'assets/images/states/oregon.png';
      case 'PA':
        return 'assets/images/states/pennsylvania.png';
      case 'RI':
        return 'assets/images/states/rhode_island.png';
      case 'SC':
        return 'assets/images/states/south_carolina.png';
      case 'SD':
        return 'assets/images/states/south_dakota.png';
      case 'TN':
        return 'assets/images/states/tennessee.png';
      case 'TX':
        return 'assets/images/states/texas.png';
      case 'UT':
        return 'assets/images/states/utah.png';
      case 'VT':
        return 'assets/images/states/vermont.png';
      case 'VA':
        return 'assets/images/states/virginia.png';
      case 'WA':
        return 'assets/images/states/washington.png';
      case 'WV':
        return 'assets/images/states/west_virginia.png';
      case 'WI':
        return 'assets/images/states/wisconsin.png';
      case 'WY':
        return 'assets/images/states/wyoming.png';
      default:
        return 'assets/images/states/usa.png';
    }
  }
}
